[package]
name = "slurm-spank-rs"
version = "0.1.0"
authors = ["Francois Diakhate <fdiakh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "slurm_spank_rs"
crate-type = ["cdylib"]

[dependencies]
byte-strings = "0.1.3"
lazy_static = "1.4.0"
libc = "0.2.94"
num_enum = "0.5.1"


