[package]
name = "slurm-spank-rs"
version = "0.1.0"
authors = ["Francois Diakhate <fdiakh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "slurm_spank_rs"
crate-type = ["cdylib"]

[dependencies]
byte-strings = "0.1.3"
enum_primitive = "0.1.1"
num = "0.4.0"


