[package]
name = "slurm-spank-example"
version = "0.1.0"
authors = ["Francois Diakhate <fdiakh@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
eyre = "0.6.8"
libc = "0.2.137"
slurm-spank = { path = "../.."}
tracing = "0.1.37"
